---
title: Seahawks offseason priorities
author: Mike Morris
date: '2021-01-06'
slug: seahawks-offseason-priorities.en-us
categories:
  - NFL
  - Seahawks
tags:
  - NFL
  - Seahawks
keywords:
  - tech

---


The NFL season is not over, but I thought this would be a good time to collect my thoughts on roster construction in general and the Seahawks situation in particular. I'm excited to compare these ideas to what the team actually does over the next six months.

The Seahawks are in a fairly good position heading into the offseason. They have one of the league’s best quarterbacks, and [quarterback is 3-10x more valuable](https://www.pff.com/news/draft-why-positional-value-matters-in-the-nfl-draft) than other positions (excluding specialists, who are even less valuable). They also have strong players at wide receiver (second most valuable), safety (third most valuable) and linebacker. 

However, the salary cap imposes limits, and Seattle does not have a lot of draft capital in 2021 (no first, no third, no sixth), making for some tough offseason choices. 

Seattle has also done well by picking up veterans mid season for lower draft picks. It’s possible that whatever holes are there at the start of next season can be addressed by trades with 2022 picks. 

## High priorities

In order from most important to least important.

### Secondary

* Defense should be built to [stop the pass first](https://michael-morris.us/2021/01/index.en-us/), and [stopping the pass begins with the secondary, not the defensive line](https://www.pff.com/news/pro-pff-data-study-coverage-vs-pass-rush). The 2020 group is decent, but will be too expensive to keep together.

* I’d be tempted to force Adams to play his last year and then see where things are at the end of next season, when he very well might walk. That said, there’s no chance of that happening after dealing more than two first round picks for him and his record setting sack numbers this year. It will probably take $17-18M per year to sign him, and it’s tough but I’m on board. 

* The best cornerback of the current group may be DJ Reed (best grade among the group at PFF). Amadi has been good, and I’m not convinced Griffin is worth the price to retain him. 
Among the safeties, Diggs and Blair should be back, and Neal has been good, so there is reasonable depth there without any additional players.

* Specific hoped for moves: Extend Adams, extend Reed before he becomes really pricey, let Griffin walk, and draft a cornerback in the 2nd round.


### Backup quarterback

* I’ll repeat my point above: I believe quarterback is 3-10x more important than any other position. It therefore makes sense to invest a lot in a backup even if the backup is unlikely to play. Career ending injuries happen all the time. 

* In the past I have liked the practice of saving resources for positions that are going to play. The problem is that Smith is not a high quality backup, and the team would sink immediately if Wilson went down. I’m now of the opinion that taking regular chances on high upside quarterback is a good idea, even if you currently have one of the best ones in the league.

* Specific hoped for moves: Let Smith walk. Invest a 4th round pick in a high upside quarterback. He’ll probably never see the field and will probably stink if he does, but there’s a better chance of striking gold earlier in the draft. If he plays and has a hot streak, he could be traded away, like the Patriots did with Garoppolo. And if Wilson goes down it's possible the backup will be good enough to take over, like Prescott did when Romo went down. 
Offensive line

* I’m not sure how but a decent offensive line finally happened in 2020. I believe that offensive lines are really important, and are deserving of strong investment, but I’m not convinced that much needs to happen here. More depth is always good here, though, and Brown is not getting any younger.

* Specific hoped for moves: Late round draft picks, games on veterans with mid level contracts (e.g., Shell). 

### Defensive line

* Early in the year this position group was not getting great reviews by the commentariat, but the second half of the season has been different. The defensive line is not a strength, but it’s not a noticeable weakness either.  There are still some ok players under contract next year, including 2020 first round pick Taylor, who didn’t play this year. 

* Specific hoped for moves: extend Dunlop if < $7M/year for two years, take gambles on veterans with mid level contracts (e.g., Mayowa)


### Tight end

* It would be fun to see what Wilson could do with a top tight end. Graham was a good try but not a great player once he got to Seattle. Dissley could be great but he has gotten hurt too much to be considered reliable. Hollister is ok. Olsen is old.

* This is a position group where teams generally do a good job selecting the top prospects, so your chances are better of getting a top tight end earlier in the draft. Unfortunately I don’t think the Seahawks should spend the draft capital this year. 

* Specific hoped for moves: Cut Olsen, use a fourth round pick, pick up veterans on minimum deals, and mostly hope Dissley stays healthy.


## Low priorities

In order from least important to most important.

### Specialists 

* Dickson and Myers are under contract and are good, let’s leave them there.

* Specific hoped for moves: None. 


### Running back

* [Running backs don’t matter](https://www.pff.com/news/nfl-rams-cardinals-showed-why-teams-should-never-invest-running-backs). That’s too strong, and I like Carson, Hyde, Penny, and the others, but the numbers suggest that [teams should be passing more](https://michael-morris.us/2020/01/seahawks-should-pass-more/) anyway, that running back performance isn’t all that important, and that teams do just as well with undrafted free agents. It makes no sense to use scarce draft and salary cap resources on this position. Even if running back play was not at the level of this year’s group, the needs at other position groups make cuts here a necessary tradeoff.

* Specific hoped for moves: Let Carson and Hyde walk, go with Penny and Dallas as first options, pick up some undrafted free agent rookies.


### Linebacker

* Wagner is under contract and Brooks looks...ok. I’ve liked watching Wright play and he’s been great this year, but he is getting up there in age and it’s difficult to pay him $10M when there are positions of higher value. We probably shouldn’t be playing three linebackers that much anyway.

* Specific hoped for moves: Sign KJ to a cheap deal <$8M/year for two years, but if that’s not possible, let him go. 

### Wide receiver

* This is an important position group, and with Metcalf and Lockett having serious injury histories, more depth would be great but there is only so much to go around.

* Specific hoped for moves: Like 2020, supplement the top two with low cost veterans and low round rookies. 


