---
title: Coronavirus questions for later
author: Mike Morris
date: '2020-05-25'
slug: coronavirus-questions-for-later
categories:
  - Apolcalypse
tags:
  - Education
  - Transportation
  - Urbanism
keywords:
  - tech

---

Things I’m curious to read about in the coming years about coronavirus impacts:

* Work related

  + Will companies become more friendly to remote work? Will they seek out remote employees as a form of resilience to future disease waves? 
  + Will they increase their demand for office space to give their employees more space or decrease their demand as they shift to remote work?
  + Will a home office boost the value of one’s house more than before?
  + Will business travel and in person meetings become relatively less common?

* Environment related
  + How much do air pollution levels go down? Do people notice that the air smells better?
  + How much quieter are cities without all the traffic?
  + Have numbers of wildlife increased?

* School related
  + Will parents become more favorable to homeschooling? Will fewer kids end up going to formal schools? Will legislation make that easier or harder to accomplish?
  + Will college students pay tens of thousands per year for remote education? 
  + Will employers become less interested in college degrees as a signal of value? Will they be more open to other credentials?
  
* Lifestyle related
  + Will attendance at large gatherings like concerts and sporting events decline?
  + Did more people end up going to local parks? Will they continue to do so?
  + Will people eat in restaurants less?
  + Will people travel to distant locales less?
  + Will cities lose their appeal?

* Health related
  + Will people continue to eat more beans?
  + Will bidets become more popular?
  + Will people cook more meals at home?
  + Will people focus more on home exercise options?

My baseline overall prediction is that one year out not much changes. I remember people asking similar kinds of questions after 9/11 (will people ever fly again?) and that seems to be a distant blip on actual behavior. 


