---
title: Coronavirus assorted thoughts
author: Mike Morris
date: '2020-03-26'
slug: coronavirus-assorted-thoughts
categories:
  - Apolcalypse
tags:
  - Transportation
  - Education
keywords:
  - tech
---

Some random thoughts and observations:

- Widespread mask usage seem like a [good idea](https://slatestarcodex.com/2020/03/23/face-masks-much-more-than-you-wanted-to-know/)
- If we have lots of easy cheap testing (and at home), it would be much easier to allow certain people to break quarantine and possibly [donate blood](https://marginalrevolution.com/marginalrevolution/2020/03/convalescent-blood-therapy.html) to help others get well.
- [Opening up the Seattle express lanes and certain other roads to bikes](https://www.seattlebikeblog.com/2020/03/26/one-idea-for-socially-distant-outdoor-space-make-roadways-like-lake-washington-blvd-and-the-i-5-express-lanes-car-free/) seem like a great limited duration idea. They are not needed at present traffic volumes, easy to monitor/police, and provide a needed entertainment outlet with so many other parks and outdoor options closed.
- If prisoners can to get and stay in shape in their cells, there is plenty of potential for doing so at home. Body weight exercises, stretching, jumping jacks - there is no shortage of ways to get fit in limited space.
- The deluge of information from our kids school is incredible. I know they are trying to be helpful (e.g., maybe you should check this out), but it's too much. Better would be if they made 5-10 minute videos with basic lessons for the day, which refer to resources that we can access at home. This would let the kids see their faces and give parents guidance on what to cover. To be fair, their latest communications make it look as if they are moving in this direction.


My current predictions, which are not terribly original:

- There will be an uptick in homeschooling. Some will really enjoy it and find that their kids do as well. 
- Education online will experience a boost, as more people will realize they don't have to be there in person to learn something. Online education scales tremendously and there are some really great resources out there. For basics I like [IXL](ixl.com).
- Big business will come out relatively ahead of small business, as they are better positioned and better capitalized to get through the crisis. 
- All of these trends will tend to [exacerbate inequality](https://www.amazon.com/Average-Over-Powering-America-Stagnation-ebook/dp/B00C1N5WOI), as the most capable and interested can take better advantage.

My hope is that in all of this we will shift a bit more toward a [Mr. Money Moustache](https://www.mrmoneymustache.com/) kind of lifestyle - with more deliberate spending choices, bigger financial buffers, and more effort on building community and relationships than fancy toys and vacations. I sort of doubt it but that's my hope.

