---
title: Walt Disney World tips
author: Mike Morris
date: '2020-03-02'
slug: walt-disney-world-tips
categories:
  - Personal
tags:
  - Theme parks
keywords:
  - tech

---

My family and I recently spent a day at Walt Disney World (Magic Kingdom) in Orlando. Here's what I recommend if you are considering going yourself:

Before you book, strongly consider not going at all. My wife and I agreed after that even though our day went ok, it was a big effort in time and money and it probably wasn't worth it. There are many other theme parks and places to go.

If you are committed to going, here is what I strongly recommend:

* Begin the process over a month before your planned arrival. 
* We found a perfectly fine AirBnB a few minutes away from the park that was much cheaper than the Disney housing options. There are some perks to staying on campus, though. 
* Get the latest version of [this book](https://www.amazon.com/Unofficial-Guide-Disneyland-2019-Guides/dp/1628090855/) and read the sections for the parks you are going to. Understand how the FastPass system works. 
* Buy your passes in advance, so that 30 days out you can make your FastPass reservations. This is very important if you want to get all the best rides in one day and not wait 2+ hours for each of several of them. 
* Get there an hour before the park opens. You will be able to walk Main Street without feeling like you are missing out on rides, you'll see the opening ditty at Cinderella's Castle, and be ready to get to a good ride when the full park opens.
* Carry around some notes about what rides you want to hit and download the app so you can see approximate wait times. In other words, spend several hours in advance to know what your priorities are.
* Carry tons of snacks and a water bottle. No need to waste time in line for iffy and expensive food, you'll spend plenty of time waiting in line for rides anyway. You can bring a backpack on the rides, so there is no storage issue. Same idea on an extra layer if weather is doubtful.  

Overall, the experience was...fine. We got on most of the major rides we wanted, but missed on others due to either bad planning on our part or mechanical issues. The kids were happy and we checked the "been to Disney" box, but we don't plan on going back any time soon.
