---
title: Busses and bikes and parking
author: Mike Morris
date: '2020-05-25'
slug: busses-and-bikes-and-parking
categories:
  - Transportation
tags:
  - Urbanism
  - Transportation
keywords:
  - tech

---

A collection of thoughts on transportation in cities: 

* [Busses are underrated](https://www.vox.com/policy-and-politics/2016/10/4/13121058/trump-clinton-infrastructure-economics-glaeser). They should be the backbone of urban public transportation. They are cost effective and can change according to demand (frequency and routes). Bus only lanes, preferences at stop lights, better signage with expected wait times and maps, and other measures can make them more effective. The virus makes this more challenging, admittedly, although I'm optimistic that we'll eventually have some combination of vaccine, protective clothing, and behavioral practices that minimize risk. The car based alternative is more congestion, most costs, and more pollution. 
* Electric bikes are underrated. Progress in the last few years has been great. Car driving speeds, taking into account the necessary frequent stops and parking in cities, is often not any better than biking speeds. Electric bikes take the work out of biking (or do the work and get some exercise), give people fresh air, and can offer much easier parking. Where I live in Seattle, they are expanding bike lanes and parking, making it more convenient and safer to ride. The big downside is that it is more dangerous than driving. With better road design and more all ages all abilities (AAA) bike infrastructure, though, safety can be dramatically improved. I've personally bought three electric bikes in the last two years and have been blown away with how useful and fun they are. 
* Street parking should generally be more expensive. City land is a scarce resource, and it should be priced accordingly. See the excellent book [The High Cost of Free Parking](https://www.amazon.com/High-Cost-Free-Parking-Updated/dp/193236496X). 
* Congestion pricing for busy areas [is a good idea](https://ops.fhwa.dot.gov/congestionpricing/cp_what_is.htm).
* Light rail is nice to ride when convenient but too expensive ([compared to busses](http://conversableeconomist.blogspot.com/2019/03/why-economist-usually-oppose-new-light.html)) and has the same virus related challenges of busses. We shouldn't do it.
* Zoning should encourage denser building, and more of it. Fewer miles of streets, sewers, and power lines to maintain keeps municipal costs down. Shorter travel times and more goods and services within walking distance is more convenient and reduces costs. These need not be high rises. Allowing backyard cottages/ADUs/DADUs/fourplexes and four story buildings can provide all the density needed. 

For more on these general ideas I recommend 

* [Strong Towns](https://www.strongtowns.org/)
* [Why some projects get built and others don't](https://www.nber.org/papers/w23686)




