---
title: NFL analytics assorted links
author: Mike Morris
date: '2020-01-17'
slug: nfl-analytics-assorted-links
categories:
  - NFL
tags:
  - NFL
keywords:
  - tech
---



What I've been reading:

* [On predicting individual offensive line play](https://www.pff.com/news/nfl-true-pass-sets-and-their-importance-to-player-evaluation)

* [Winning leads to rushing attempts, not the other way around](https://www.footballoutsiders.com/stat-analysis/2003/establishment-clause)
 
>early in games, it is more important to gain yards than just to run the ball for the heck of it, but at the end of the game the number of runs is more important than how many yards they gain.

* What the nerds mean when the say [running backs don't matter](https://gist.github.com/guga31bb/f2a9b4e83539299405556e9ab5a36cec)...and other great bits.

> Summary: the most convincing recent evidence we have is from the Big Data Bowl, where the winning entry found that the best prediction of the result of a running play -- given the positioning of the offense and defense at the time of handoff -- can be made by ignoring the identity of the running back. This means that in a predictive sense, the only channel through which running backs "matter" on run plays is their position and acceleration at the time of the handoff. But there isn't much evidence that that's something that's stable for players over time.




